

apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: mongo
type: Opaque
data:
  mongodb-username: bW9uZ29kYmQ=    # Base64 encoded value for username 'mongodb'
  mongodb-password: YWRtaW4=          # Base64 encoded value for password 'admin'


