
apiVersion: v1                            # API version for Service resource
kind: Service                              # Resource type
metadata:                                   # Metadata about the Service
  name: mongo-express                      # Name of the Service
  namespace: mongo                         # Namespace where the Service is created
spec:                                      # Specification for the desired state
  selector:                                # Selector for Pods managed by this Service
    app: mongo-express                     # Label selector to identify the Pods
  ports:                                   # Ports configuration for the Service
    - port: 8081                           # Port exposed by the Service
      targetPort: 8081                     # Port on the Pod to forward traffic to
  type: NodePort                           # Use NodePort to expose the service externally


