

apiVersion: v1
kind: Secret
metadata:
  name: mongo-express-secret
  namespace: mongo
type: Opaque
data:
  express-username: ZXhwcmVzcz==    # Base64 encoded value for username 'express'
  express-password: YWRtaW4=          # Base64 encoded value for password 'admin'
